### ISSUE TITLE
Brainstorming/Idea Collection

### ISSUE THREAD

**Issue by Yamor123** [Ekkelus/REY-Mod#19]
This will be a collection of ideas, that came to my mind at some point but aren't worth to be openened in an extra issue (maybe because the change is too small or we aren't sure if it is possible without source code access/at all). Also, those are just ideas im not necessarily saying that we should add those features. Honestly, some of those features are maybe better left to Strangeloopgames^^. Feel free to add your own ideas.
- more uses for gold, maybe housing decoration?
- Fish -> Fishoil ?
- high quality bed, Kitchen has Refrigerator with 10 Points and some other 3-4 point things, Bathroom has 20 points washing machine, and bedroom only has the 4 point wooden fabric bed
- some sort of transport system (easiest way: crafting station wich crafts item x to x, item will be move depending on link settings) (more advanced, use pipes for moving of items)
- more power to the world leader, like maybe add the ability to instapass laws if they already have a set amount of votes and no or only a small percentage of no votes (/passlaws lite version for world leader)
- Water: Waterpump can pump freshwater or saltwater, saltwater needs to be processed into freshwater and salt, salt can be used for food.. Rainwatercollector, maybe Dirty/polluted water?
- <s>Upgrades (hewn log to lumber for example), deep specialisation through efficiency combination?</s>
- /away to set up a away notice to prevent unclaiming of property ... alternatively an AwayMarker as placeable object. (You may ask why this and not signs? because i could iterate through all objects of that type and get a list of their owners that way, signs are used for other things too, so thats not good)
- <s>/nutritionranking, same thing as /houseranking but for your food sp, so you can see who is eating the healthiest^^</s>

- State Lottery (your idea, should be possible to do, but i'd like a bit more input about how the system should work in your opinion)

- (probably very hard to do) Special shop type, barter trade station: a shop where you can setup barter trades instead of working with currency, great for processed goods for raw material deals, or repair deals. 
Would be nice if its still possible to add a fee, so for example trade 1 Brick for 10 Stone and 1 sbc, or trading a new pickaxe for a broken one + 5sbc/5ingots

- bees
- new plants
- Logging, Mining, Digging changes, (either buff or move)
- (probably very hard to do) government owned Shop/Contracts: as world leader being able to set up shops or contracts that use government funds,
- government owned property: Townhall wich is automatically owned/manageable by the current world leader
- make it easier for the worldleader to setup taxes/payments for specific actions, i mean the normal taxes can be changed in a minute alone by the decision of the leader, he also can easily (manually) distribute government funds... but if he wants to automatically pay people for building roads in the roads disctrict, he has to propoes a law, wich will take a day to pass, he also can only have one law proposal open at any time. Thats severely limiting the abitily to rule.
- (probably very hard to do) Greenhouses
- more to come...

**Comment by Ekkelus** [comment]
Restrict non hunters from hunting.

**Comment by Ekkelus** [comment]
/avatar
/avatar, Yamor

Show information about you or any other player like:
House value
Total claimed land
Profession?
Money
And perhaps future stuff.

**Comment by Yamor123** [comment]
Kinda same topic as your food allergies would be the concept of Diseases, we could also add medicine then. We already have a crafting station for that in the game (and it isnt even used yet as the skill it is meant for is not finished yet)

**Comment by Ekkelus** [comment]
What kind of effect will a disease have on a player? And what crafting station are you talking about? The Lab?

**Comment by Yamor123** [comment]
yeah i meant the lab. possible effects could be for example Higher Calorie Consumption, lower movement speed, lower weight capacity, lower SP rate, maybe lower logging dmg (more hits per tree, but we should add something equivalent for mining then too).
