### ISSUE TITLE
Note about changes for next wipe

### ISSUE THREAD

**Issue by Yamor123** [Ekkelus/REY-Mod#20]
~~- Construction Skills under Self Improvement (i would split it in 4 different skills, so there is T1,T2,T3 and T4 construction, maybe all only 1 level or the same 4 levels we have now)~~

**Comment by Ekkelus** [comment]
Increase overall laser requirements

**Comment by Ekkelus** [comment]
- Add more books to top tier research
- Can paper be used for more things?

**Comment by Ekkelus** [comment]
Nutrition values for:
- Honey Glazed Ham
- Honey Flan
- Honey Bun

Description for
- Honey Glazed Ham
- Honey Flan
- Honey Bun

Recipe for
- Honey Glazed Ham
- Honey Flan
- Honey Bun

Crafting table for
- Honey Glazed Ham
- Honey Flan
- Honey Bun

**Comment by Ekkelus** [comment]
Hunter skins animals at butchery table (General skill)

**Comment by Ekkelus** [comment]
Check if it's possible to force wind turbine to be placed on 3x3 reinforced concrete

**Comment by Ekkelus** [comment]
Balance recipes for:
- Plough
- Skid Steer
- Truck
- Wheelbarrow

**Comment by Ekkelus** [comment]
Get as many professions involved in making Lasers and Computer Labs

**Comment by Ekkelus** [comment]
Spawn
